name: dl
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - ipykernel
  - pip
  - pip:
    - tensorflow[and-cuda]
    - seaborn
    - scikit-learn
